@startuml
title Diagrama de Classes — Domínio do Cinema

class Cinema {
  +id
  +nome
  +capacidade
  +endereco
}

class Filme {
  +id
  +titulo
  +duracao_min
  +genero
  +diretor
  +elenco
}

class Sessao {
  +id
  +inicio
  +fim
}

class Publico {
  +id
  +data
  +quantidade
}

Cinema "1" -- "N" Sessao
Filme "1" -- "N" Sessao
Sessao "1" -- "N" Publico
@enduml
